### ISSUE TITLE
Plugin 'Protocol Buffer Editor' (version '2.2.0') is not compatible with IntelliJ 2021.1

### ISSUE THREAD

**Issue by koalazub** [google/intellij-protocol-buffer-editor#3]
I'm unable to utilise `.proto` autocompletion using the package you've got listed in the marketplace. 

Has this package been abandoned and if so, where should I look for a package that supports protobuf?

**Comment by jvolkman** [comment]
This repo was never supported. You're looking for https://github.com/jvolkman/intellij-protobuf-editor.

**Comment by koalazub** [comment]
Oops, did not know that. I'll close this off. Did you want me to port this over to https://github.com/jvolkman/intellij-protobuf-editor?

**Comment by jvolkman** [comment]
No need; https://github.com/jvolkman/intellij-protobuf-editor/issues/53 is already open.

**Comment by koalazub** [comment]
Too easy. Cheers.
